[package]
name = "the_resumator"
version = "0.1.2"
edition = "2021"

[dependencies]
bevy = { version = "0.8.1" }
rand = "0.8.5"

[profile.release]
opt-level = "s"
lto = "thin"

[[bin]]
name = "index"
path = "src/main.rs"
