[package]
name = "mass_gathering"
version = "0.8.0"
edition = "2021"

[dependencies]
bevy = "0.8.1"
bevy_egui = "0.16.1"
bevy_rapier3d = "0.18.0"
egui = "0.19.0" # can't I use these "through" bevy_egui?
egui_extras = "0.19.0" # bin size bloat?
rand = "0.8.5"
rapier3d = "0.16.0"
web-sys = { version = "0.3.60", features = ["Window"] }

[profile.release]
opt-level = "s"
lto = "thin"

[[bin]]
name = "index"
path = "src/main.rs"

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3
