[package]
name = "mass_gathering"
version = "0.10.9"
edition = "2021"

[dependencies]
bevy = { version = "0.9.0", features = ["bevy_asset", "bevy_winit", "render", "png",] }
bevy_egui = "0.17.1"
bevy_rapier3d = "0.19.0"
egui = "0.19.0"
egui_extras = "0.19.0"
rand = "0.8.5"
rapier3d = "0.16.1"
web-sys = { version = "0.3.60", features = ["Window"] }

[profile.release]
opt-level = "s"
lto = "thin"

[[bin]]
name = "index"
path = "src/main.rs"

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3
