[package]
name = "mass_gathering"
version = "0.3.1"
edition = "2021"

[dependencies]
bevy = "0.8.1"
bevy_egui = "0.16.1"
bevy_rapier3d = { git = "https://github.com/dimforge/bevy_rapier.git" }
rand = "0.8.5"

[profile.release]
opt-level = "s"
lto = "thin"

[[bin]]
name = "index"
path = "src/main.rs"

# Oops. Forgot about these (recommended by Bevy Book. Likewise above `"dynamic"`)

[profile.dev]
opt-level = 1
#debug = 1 # <-- a "maybe"

[profile.dev.package."*"]
opt-level = 3
