[package]
name = "mass_gathering"
version = "0.11.0"
edition = "2021"

[dependencies]
bevy = { version = "0.9.0", default-features = false, features = ["bevy_winit", "bevy_core_pipeline", "bevy_pbr"] }
#bevy_egui = { version = "0.17.1", default-features = false, features = ["default_fonts"] }
bevy_egui = "0.17.1"
bevy_rapier3d = { version = "0.19.0", default-features = false, features = ["dim3"] }
serde = { version = "1.0", features = [ "derive" ] }
bevy_renet = "0.0.6"
egui = "0.19.0"
egui_extras = "0.19.0"
rand = "0.8.5"
rapier3d = "0.16.1"
bincode = "1.3.3"
web-sys = { version = "0.3.60", default-features = false, features = ["Window"] }
clap = { version = "4.0.27", features = ["derive"] }
renet_visualizer = { version = "0.0.3", features = ["bevy"] }
smooth-bevy-cameras = { git = "https://github.com/bonsairobo/smooth-bevy-cameras", rev="138835" }

[profile.release]
opt-level = "s"
lto = "thin"

[[bin]]
name = "index"
path = "src/main.rs"

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3
