[package]
name = "mass_gathering"
version = "0.30.0"
edition = "2021"
default-run = "server"

[dependencies]
bevy = { version = "0.9.1", default-features = false, features = ["bevy_winit", "bevy_core_pipeline", "bevy_pbr"] }
bevy_rapier3d = { version = "0.19.0", default-features = false, features = ["dim3"] }
serde = { version = "1.0.152", features = [ "derive" ] }
bevy_renet = "0.0.6"
bincode = "1.3.3"
bevy_egui = "0.18.0"
clap = { version = "4.0.32", features = ["derive"] }
rand = "0.8.5"

[profile.release]
opt-level = "s"
lto = "thin"

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3
