[package]
name = "mg_renet_play"
version = "0.3.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3

[dependencies]
bevy_rapier3d = "0.19.0"
bevy = { version = "0.9.0", default-features = false, features = ["bevy_core_pipeline", "bevy_asset", "bevy_render", "bevy_pbr", "x11"] }
serde = { version = "1.0", features = [ "derive" ] }
bincode = "1.3.1"
bevy_egui = "0.17.1"
# TODO: when released, use new version with bevy 0.8
smooth-bevy-cameras = { git = "https://github.com/bonsairobo/smooth-bevy-cameras", rev="138835" }
bevy_renet = "0.0.6"
renet_visualizer = { version = "0.0.3", features = ["bevy"] }

