[package]
name = "the_resumator"
version = "0.1.2"
edition = "2021"

[dependencies]
bevy = { version = "0.8.1" }
bevy_egui = "0.16.1"
bevy_prototype_lyon = "0.6.0"
bevy_rapier3d = "0.17.0"
heron = { version = "4.0.2", features = ["3d"] }
particular = "0.2.0"
rand = "0.8.5"
rapier3d = "0.15.0"

[profile.release]
opt-level = "s"
lto = "thin"

[[bin]]
name = "index"
path = "src/main.rs"
